### ISSUE TITLE
prepare for translation

### ISSUE THREAD

**Issue by TomTasche** [opendocument-app/OpenDocument.ios#15]
the Android app was translated to lots of languages already: https://crowdin.com/project/opendocument

we should leverage those translations as much as possible. prepare the project so the above translations can be used

**Comment by TomTasche** [comment]
"prepare" in this case means extracting strings to the appropriate file format in Xcode

**Comment by TomTasche** [comment]
try to reuse the same string names from Android so we can easily sync them. Crowdin allows to download strings in ios format too

**Comment by Metaxa007** [comment]
[Localizable.strings](https://github.com/opendocument-app/OpenDocument.ios/files/4405724/iOS.zip)

**Comment by TomTasche** [comment]
https://github.com/opendocument-app/OpenDocument.ios/pull/49

**Comment by TomTasche** [comment]
this is what I see after switching to German via the system settings:
<img width="491" alt="Screenshot 2020-04-05 at 08 38 59" src="https://user-images.githubusercontent.com/128734/78468505-ff0a3180-7718-11ea-9fc9-4d5b7cf841c1.png">

**Comment by TomTasche** [comment]
https://github.com/opendocument-app/OpenDocument.ios/pull/50

**Comment by TomTasche** [comment]
Some UI strings like "Back to documents" are still hardcoded.

**Comment by TomTasche** [comment]
Afterwards we have to make sure all iOS strings are available on CrowdIn too.

**Comment by TomTasche** [comment]
https://github.com/opendocument-app/OpenDocument.ios/pull/56
