### ISSUE TITLE
MacOS app

### ISSUE THREAD

**Issue by TomTasche** [opendocument-app/OpenDocument.ios#21]
we should be able to reuse most of the code written for the iOS app to also make it usable on MacOS

**Comment by jeed2424** [comment]
True, but do you think it is really necessary to make it as a MacOs app? I mean, openoffice and libreoffice are already available on MacOs... So what purpose would it serve? It would be great on iOS and seems like people like it on Android and there's a reason: demand!

**Comment by TomTasche** [comment]
Generally yes, I agree. A few reasons it's still worth a try in my opinion:
- Apple is working on "Project Marzipan" which would allow easy porting of iOS apps to Mac
- LibreOffice is also available on Android. Our advantage is a very small app size
- Users also use this app for other file formats, e.g. PDF, docx, etc. This makes it very visible in an app store

What do you think?

**Comment by jeed2424** [comment]
Didn't know the app could open all these types of files, which makes it even more interesting! The size of the app is definitely something people consider on cellphones, so I  agree with the advantage here. 

As far as the MacOS app goes, _IF_ Apple's "Project Marzipan" works, it'd be worth a try, but I believe that it would be better to get people to use the iOS version (getting them hooked of sorts) and then release a MacOS app, hoping that they will switch from whatever they were using before to something "more familiar" and if we can get the basics of connecting multiple devices together, then users could open a file on any device (much like Google Drive does or whatever).

So my official answer is: Yes, but in due time.

**Comment by TomTasche** [comment]
Agreed! Last time I checked Project Marzipan was not publicly available anyway. In the mean time the main goal is to get users hooked on the iOS app of course!

**Comment by TomTasche** [comment]
I'd be happy to hear your suggestions how we could make the iOS app more attractive for users by the way

**Comment by jeed2424** [comment]
Sounds good! I haven’t checked the code/app yet, so I’ll do that and give you feedback later tonight!

**Comment by jeed2424** [comment]
I finally got Mojave running and checked what you have. I have a few problems that I can resolve on my own, but you didn't include "TranslationHelper.h" and other files on the repository... Also, if you want your app to be released on the app store, you HAVE TO use Xcode 10 in swift 5 (updated my system to Mojave for that exact reason).

**Comment by TomTasche** [comment]
Regarding the missing files you most likely have to run "git submodule update --init --recursive" in order to download all dependencies. I'll add that to the README as soon as I'm working on that again.

I'll also make sure to migrate to Swift 5. Last time I worked on it it wasn't a requirement yet. Thanks for bringing that up!

**Comment by jeed2424** [comment]
Sounds good, I'll try that tomorrow! (It's currently 2:20 am here!)

**Comment by TomTasche** [comment]
FYI I migrated to Swift 5 now (see commit above). It went through without any errors for me, but took quite a while. Ping me if something else is not working for you @jeed2424

**Comment by TomTasche** [comment]
Seems easily possible with Xcode 11 (currently in beta): https://developer.apple.com/documentation/uikit/creating_a_mac_version_of_your_ipad_app?utm_campaign=iOS%2BDev%2BWeekly&utm_medium=rss&utm_source=iOS%2BDev%2BWeekly%2BIssue%2B407

**Comment by TomTasche** [comment]
This is possible now as of Xcode 11 and macOS 10.15. Fails for me though because it doesn't build the cpp-dependencies for some reason and eventually fails with:

> clang: error: no such file or directory: '/Users/tom/Library/Developer/Xcode/DerivedData/OpenDocumentReader-dcebjuwktjsesycjykztwgxygixx/Build/Products/Release-maccatalyst/libtinyxml2.a'
> clang: error: no such file or directory: '/Users/tom/Library/Developer/Xcode/DerivedData/OpenDocumentReader-dcebjuwktjsesycjykztwgxygixx/Build/Products/Release-maccatalyst/libglog.a'
> clang: error: no such file or directory: '/Users/tom/Library/Developer/Xcode/DerivedData/OpenDocumentReader-dcebjuwktjsesycjykztwgxygixx/Build/Products/Release-maccatalyst/libminiz.a'
> clang: error: no such file or directory: '/Users/tom/Library/Developer/Xcode/DerivedData/OpenDocumentReader-dcebjuwktjsesycjykztwgxygixx/Build/Products/Release-maccatalyst/libodrlib.a'
> Command Ld failed with a nonzero exit code

**Comment by TomTasche** [comment]
related: https://github.com/leetal/ios-cmake/issues/53

**Comment by TomTasche** [comment]
According to Apple, our app is automatically going live for Mac soon.
