### ISSUE TITLE
Filtering

### ISSUE THREAD

**Issue by jeed2424** [opendocument-app/OpenDocument.ios#25]
*I didn't know the app was on the app store, so congrats on that!* When I first opened the app and tried to open a file, I noticed that everything that isn't supported is just greyed (actually, the opacity is just lowered but wtv)... I was wondering if there was a way to filter this kind of stuff and just show the types of documents that are supported by the app...

**Comment by jeed2424** [comment]
![IMG_2035](https://user-images.githubusercontent.com/50756835/58000014-72756700-7aa5-11e9-88e4-cfb7cdaf5cad.PNG)
Just an example of my view

**Comment by TomTasche** [comment]
Good question. I'm using a standard component for rendering the file browser. As far as I know there is no option to change this particular behavior, but it's worth doing some research. In the worst case it would require rewriting the whole file browser from scratch...
